INSERT INTO user (email, password, role, lastname) VALUES ('admin1@test.com', '$2a$10$FiH8giEy6sJeOv0SUBSBD.Vo4Qgmn5pjuXqEIn1L8xQrSfXYqojpG', 'ROLE_ADMIN', 'test');
INSERT INTO user (email, password, role) VALUES ('test123@test.com', '$2a$10$FiH8giEy6sJeOv0SUBSBD.Vo4Qgmn5pjuXqEIn1L8xQrSfXYqojpG', 'ROLE_USER');

INSERT INTO user (email, password, role) VALUES ('test@test.com', '$2a$10$FiH8giEy6sJeOv0SUBSBD.Vo4Qgmn5pjuXqEIn1L8xQrSfXYqojpG', 'ROLE_USER');
INSERT INTO user (email, password, role, firstname, lastname, picture_url, description) VALUES ('admin@test.com', '$2a$10$FiH8giEy6sJeOv0SUBSBD.Vo4Qgmn5pjuXqEIn1L8xQrSfXYqojpG', 'ROLE_USER', 'admin', 'test', 'https://media.wired.com/photos/598e35fb99d76447c4eb1f28/16:9/w_2123,h_1194,c_limit/phonepicutres-TA.jpg', 'teetstst tsts');


INSERT INTO product (name, price, stock, picture_url, category) VALUES ('Animal Crossing: New Horizons', 59.99, 10, 'https://fs-prod-cdn.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_5/SQ_NSwitch_AnimalCrossingNewHorizons_image500w.jpg', 'Aventure');
INSERT INTO product (name, price, stock, picture_url, category) VALUES ('Mario Kart 8 Deluxe', 69.99, 5, 'https://fs-prod-cdn.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_5/SQ_NSwitch_MarioKart8Deluxe_image500w.jpg', 'Course');
INSERT INTO product (name, price, stock, picture_url, category) VALUES ('The Legend of Zelda: Tears of the Kingdom', 69.99, 2, 'https://fs-prod-cdn.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_5/1x1_NSwitch_TloZTearsOfTheKingdom_BASE_image500w.jpg', 'Aventure');
INSERT INTO product (name, price, stock, picture_url, category) VALUES ('New Super Mario Bros. U Deluxe', 59.99, 4, 'https://fs-prod-cdn.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_5/SQ_NSwitch_NewSuperMarioBrosUDeluxe_image500w.jpg', 'Plateforme');
INSERT INTO product (name, price, stock, picture_url, category) VALUES ('No Place Like Home', 24.99, 4, 'https://fs-prod-cdn.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_5/1x1_NSwitch_NoPlaceLikeHome_image500w.jpg', 'Action');
INSERT INTO product (name, price, stock, picture_url, category) VALUES ('Shovel Knight: King of Cards', 8.99, 4, 'https://fs-prod-cdn.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_download_software/SQ_NSwitchDS_ShovelKnightKingOfCards_image500w.jpg', 'Action');
INSERT INTO product (name, price, stock, picture_url, category) VALUES ('ARK: Survival Evolved', 19.99, 4, 'https://fs-prod-cdn.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_5/SQ_NSwitch_ARKSurvivalEvolved_image500w.jpg', 'Aventure');
INSERT INTO product (name, price, stock, picture_url, category) VALUES ('ARK: Survival Evolved', 19.99, 4, 'https://fs-prod-cdn.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_5/SQ_NSwitch_ARKSurvivalEvolved_image500w.jpg', 'Aventure');